---
local_work_dir: "/home/asatxisija2"
remote_work_dir: "/home/asatxisija2"
git_repo: "https://github.com/ridzzbahar/parkir.git"
dh_user: "bahaaar29"
dh_pass: "Faridganteng1"
image_name: "parkingapp_faridz:v1"
